/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Carriage: THREE.Mesh
    Wheel_4: THREE.Mesh
    Wheel_3: THREE.Mesh
    Wheel_6: THREE.Mesh
    Wheel_5: THREE.Mesh
    Wheel_1: THREE.Mesh
    Wheel_2: THREE.Mesh
    Interior: THREE.Mesh
    Carriage001: THREE.Mesh
  }
  materials: {
    Carriage: THREE.MeshStandardMaterial
    ['Dark Metal']: THREE.MeshStandardMaterial
    Interior: THREE.MeshStandardMaterial
    Roof: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/train.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carriage.geometry}
        material={materials.Carriage}
        position={[0, 1.22, 0]}
        scale={[1, 1, 3.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_4.geometry}
        material={nodes.Wheel_4.material}
        position={[0, 0.22, 0.3]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_3.geometry}
        material={nodes.Wheel_3.material}
        position={[0, 0.22, -0.3]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_6.geometry}
        material={nodes.Wheel_6.material}
        position={[0, 0.22, 2.33]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_5.geometry}
        material={nodes.Wheel_5.material}
        position={[0, 0.22, 1.73]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_1.geometry}
        material={nodes.Wheel_1.material}
        position={[0, 0.22, -2.33]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel_2.geometry}
        material={nodes.Wheel_2.material}
        position={[0, 0.22, -1.73]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.15, 19.05, 1.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior.geometry}
        material={materials.Interior}
        position={[0, 1.31, 0]}
        scale={[0.91, 0.5, 3.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carriage001.geometry}
        material={materials.Roof}
        position={[0, 1.22, 0]}
        scale={[1, 1, 3.75]}
      />
    </group>
  )
}

useGLTF.preload('/train.glb')