/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/suv-luxury/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft017.geometry}
        material={nodes.Mesh_wheel_frontLeft017.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft017_1.geometry}
        material={nodes.Mesh_wheel_frontLeft017_1.material}
      />
      <mesh
        geometry={nodes.Mesh_body018.geometry}
        material={materials["plastic.005"]}
      />
      <mesh
        geometry={nodes.Mesh_body018_1.geometry}
        material={materials.paintYellow}
      />
      <mesh
        geometry={nodes.Mesh_body018_2.geometry}
        material={materials["_defaultMat.005"]}
      />
      <mesh
        geometry={nodes.Mesh_body018_3.geometry}
        material={materials["lightBack.005"]}
      />
      <mesh
        geometry={nodes.Mesh_body018_4.geometry}
        material={materials["window.004"]}
      />
      <mesh
        geometry={nodes.Mesh_body018_5.geometry}
        material={materials["lightFront.005"]}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft016.geometry}
        material={nodes.Mesh_wheel_frontLeft016.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft016_1.geometry}
        material={nodes.Mesh_wheel_frontLeft016_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft018.geometry}
        material={nodes.Mesh_wheel_frontLeft018.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft018_1.geometry}
        material={nodes.Mesh_wheel_frontLeft018_1.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft015.geometry}
        material={nodes.Mesh_wheel_frontLeft015.material}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft015_1.geometry}
        material={nodes.Mesh_wheel_frontLeft015_1.material}
      />
    </group>
  );
}

useGLTF.preload(
  "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/suv-luxury/model.gltf"
);
