/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/taxi/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={1.3}>
        <mesh
          geometry={nodes.Mesh_body003.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes.Mesh_body003_1.geometry}
          material={materials.paintYellow}
        />
        <mesh
          geometry={nodes.Mesh_body003_2.geometry}
          material={materials.lightFront}
        />
        <mesh
          geometry={nodes.Mesh_body003_3.geometry}
          material={materials._defaultMat}
        />
        <mesh
          geometry={nodes.Mesh_body003_4.geometry}
          material={materials.window}
        />
        <mesh
          geometry={nodes.Mesh_body003_5.geometry}
          material={materials.lightBack}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight001.geometry}
          material={nodes.Mesh_wheel_frontRight001.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight001_1.geometry}
          material={nodes.Mesh_wheel_frontRight001_1.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight002.geometry}
          material={nodes.Mesh_wheel_frontRight002.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight002_1.geometry}
          material={nodes.Mesh_wheel_frontRight002_1.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight003.geometry}
          material={nodes.Mesh_wheel_frontRight003.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight003_1.geometry}
          material={nodes.Mesh_wheel_frontRight003_1.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight.geometry}
          material={nodes.Mesh_wheel_frontRight.material}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontRight_1.geometry}
          material={nodes.Mesh_wheel_frontRight_1.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/taxi/model.gltf"
);
