/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/van/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={1.2}>
        <group position={[0, 0.2, -0.1]}>
          <mesh
            geometry={nodes.Mesh_body.geometry}
            material={materials.plastic}
          />
          <mesh
            geometry={nodes.Mesh_body_1.geometry}
            material={materials.paintBlue}
          />
          <mesh
            geometry={nodes.Mesh_body_2.geometry}
            material={materials.lightFront}
          />
          <mesh
            geometry={nodes.Mesh_body_3.geometry}
            material={nodes.Mesh_body_3.material}
          />
          <mesh
            geometry={nodes.Mesh_body_4.geometry}
            material={materials.lightBack}
          />
          <mesh
            geometry={nodes.Mesh_body_5.geometry}
            material={materials.window}
          />
        </group>
        <group position={[-0.35, 0.3, 0.76]} scale={[-1, 1, 1]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={nodes.Mesh_wheel_frontLeft.material}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={nodes.Mesh_wheel_frontLeft_1.material}
          />
        </group>
        <group position={[0.35, 0.3, 0.76]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={nodes.Mesh_wheel_frontLeft.material}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={nodes.Mesh_wheel_frontLeft_1.material}
          />
        </group>
        <group position={[-0.35, 0.3, -0.76]} scale={[-1, 1, 1]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={nodes.Mesh_wheel_frontLeft.material}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={nodes.Mesh_wheel_frontLeft_1.material}
          />
        </group>
        <group position={[0.35, 0.3, -0.76]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft.geometry}
            material={nodes.Mesh_wheel_frontLeft.material}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
            material={nodes.Mesh_wheel_frontLeft_1.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/van/model.gltf"
);
